"""new fields in BneHistory table

Revision ID: 71f196774f69
Revises: a792a2c40dca
Create Date: 2025-07-31 18:18:17.521045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f196774f69'
down_revision = 'a792a2c40dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bme_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_temperature_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_temperature_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('min_humidity_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_humidity_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('min_pressure_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_pressure_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bme_history', schema=None) as batch_op:
        batch_op.drop_column('max_pressure_time')
        batch_op.drop_column('min_pressure_time')
        batch_op.drop_column('max_humidity_time')
        batch_op.drop_column('min_humidity_time')
        batch_op.drop_column('max_temperature_time')
        batch_op.drop_column('min_temperature_time')

    # ### end Alembic commands ###
