"""bme280outer_table

Revision ID: 91c221e7295f
Revises: e933ecd478df
Create Date: 2025-03-17 11:43:46.723142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c221e7295f'
down_revision = 'e933ecd478df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bme280_outer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme280_outer_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme280_outer_created_at'))

    op.drop_table('bme280_outer')
    # ### end Alembic commands ###
