"""sensor tables

Revision ID: a792a2c40dca
Revises: 
Create Date: 2025-04-06 14:07:22.503444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a792a2c40dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bme280_outer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme280_outer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bme280_outer_date'), ['date'], unique=False)

    op.create_table('bme280_rpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme280_rpi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme280_rpi_created_at'), ['created_at'], unique=False)

    op.create_table('bme_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('min_temperature', sa.Float(), nullable=False),
    sa.Column('max_temperature', sa.Float(), nullable=False),
    sa.Column('min_humidity', sa.Float(), nullable=False),
    sa.Column('max_humidity', sa.Float(), nullable=False),
    sa.Column('min_pressure', sa.Integer(), nullable=False),
    sa.Column('max_pressure', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme_history_date'), ['date'], unique=False)

    op.create_table('dht22',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature1', sa.Float(), nullable=False),
    sa.Column('humidity1', sa.Float(), nullable=False),
    sa.Column('temperature2', sa.Float(), nullable=False),
    sa.Column('humidity2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dht22', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dht22_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dht22', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dht22_created_at'))

    op.drop_table('dht22')
    with op.batch_alter_table('bme_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme_history_date'))

    op.drop_table('bme_history')
    with op.batch_alter_table('bme280_rpi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme280_rpi_created_at'))

    op.drop_table('bme280_rpi')
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme280_outer_date'))
        batch_op.drop_index(batch_op.f('ix_bme280_outer_created_at'))

    op.drop_table('bme280_outer')
    # ### end Alembic commands ###
