"""sensor tables

Revision ID: a8280cb336c3
Revises: 
Create Date: 2025-03-28 12:40:34.590470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8280cb336c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bme280_outer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme280_outer_created_at'), ['created_at'], unique=False)

    op.create_table('bme280_rpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bme280_rpi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bme280_rpi_created_at'), ['created_at'], unique=False)

    op.create_table('dht22',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature1', sa.Float(), nullable=False),
    sa.Column('humidity1', sa.Float(), nullable=False),
    sa.Column('temperature2', sa.Float(), nullable=False),
    sa.Column('humidity2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dht22', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dht22_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dht22', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dht22_created_at'))

    op.drop_table('dht22')
    with op.batch_alter_table('bme280_rpi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme280_rpi_created_at'))

    op.drop_table('bme280_rpi')
    with op.batch_alter_table('bme280_outer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bme280_outer_created_at'))

    op.drop_table('bme280_outer')
    # ### end Alembic commands ###
